import {
  BarChart3,
  CalendarDays,
  Calculator,
  Car,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  CircleDollarSign,
  FileCheck,
  FileText,
  Image as ImageIcon,
  LayoutGrid,
  Package,
  PhoneCall,
  RefreshCw,
  Send,
  Target,
  Users,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const appToolIconMap: Record<string, LucideIcon> = {
  Calculator,
  Car,
  CalendarDays,
  Image: ImageIcon,
  FileCheck,
  CheckSquare,
  ClipboardList,
  CircleDollarSign,
  PhoneCall,
  Send,
  Target,
  Users,
  Wrench,
  Package,
  BarChart3,
  RefreshCw,
  FileText,
  ClipboardCheck,
};

export const getAppToolIcon = (iconName: string): LucideIcon => appToolIconMap[iconName] || LayoutGrid;
